.publish-eo: &publish-eo
  - name: 部署正式环境
    imports:
      - https://cnb.cool/linshi-2026/env/-/blob/main/tencent_edgeone.yml
    image: tencentcom/deploy-eopages:latest
    script: edgeone makers deploy ./index.html -n wavedrom-gui -t $EO_SECRET
main:
  # tag 触发：多环境部署流程（staging / production）
  tag_push:
    production:
      stages:
        - <<: *publish-eo