#!/usr/bin/env node
'use strict';
/* Generate media/modern-render.browser.js — a browser IIFE wrapping the skill's
 * CommonJS render-modern.js. The only `require`s inside render-modern.js are
 * best-effort font-config/font-embed lookups wrapped in try/catch, so a
 * throwing `require` stub makes it fall back to built-in font stacks.
 *
 * Also copies the repo-root index.html (the visual editor UI) into media/, so
 * the packaged VSIX is self-contained: outside the repo, ../index.html does not
 * exist and the editor panel would fail to open. */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, '..', 'SKILL', 'wavedrom-render', 'lib', 'render-modern.js');
const OUT = path.join(ROOT, 'media', 'modern-render.browser.js');
const EDITOR_SRC = path.join(ROOT, '..', 'index.html');
const EDITOR_OUT = path.join(ROOT, 'media', 'editor.html');

/* 扩展版本与仓库 tag 对齐：最新 tag（vYYMMDD.N）去 'v' 补 '.0' → 合法 semver
   （260913.6.0），并随日期与序号单调递增，满足 VS Code 的更新比较。
   手打 tag 后任何一次 build/package 都会把 package.json 的 version 对齐过去，
   无需人工记改；无 git 或无 tag（浅克隆、纯目录）时保持现有 version 不动。 */
function alignVersionFromTag() {
  try {
    const tag = require('child_process').execSync('git describe --tags --abbrev=0', { cwd: ROOT, encoding: 'utf8' }).trim();
    const m = /^v(\d+)\.(\d+)(?:\.(\d+))?$/.exec(tag);
    if (!m) return;
    const ver = `${m[1]}.${m[2]}.${m[3] || 0}`;
    const pkgPath = path.join(ROOT, 'package.json');
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
    if (pkg.version === ver) return;
    pkg.version = ver;
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
    console.log('version ' + pkg.version + ' -> ' + ver + ' (from tag ' + tag + ')');
  } catch (e) { /* 无 git / 无 tag：沿用现有 version */ }
}
alignVersionFromTag();

const src = fs.readFileSync(SRC, 'utf8');
const out = `/* Generated by scripts/build.js — do not edit. Browser wrapper around
 * SKILL/wavedrom-render/lib/render-modern.js (require calls are stubbed; the
 * renderer falls back to its built-in font stacks). */
(function () {
  var mod = { exports: {} };
  (function (module, exports, require, __dirname, __filename) {
${src}
  })(mod, mod.exports, function (name) {
    throw new Error('browser build: require("' + name + '") is unavailable');
  }, '.', 'render-modern.js');
  window.WaveDromModern = mod.exports;
  /* VS Code 用 <script async> 注入预览脚本，preview.js 可能先于本文件执行完；
     挂上全局后立刻广播，让 preview.js 不必靠执行顺序也能补扫 */
  try { window.dispatchEvent(new Event('wavedrom-renderer-ready')); } catch (e) { /* noop */ }
})();
`;
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, out);
console.log('wrote ' + OUT + ' (' + out.length + ' bytes)');

fs.copyFileSync(EDITOR_SRC, EDITOR_OUT);
console.log('copied ' + EDITOR_SRC + ' -> ' + EDITOR_OUT + ' (' + fs.statSync(EDITOR_OUT).size + ' bytes)');

/* 宿主侧渲染器（hover 悬浮预览 / 预览面板用）：render-modern.js 无 DOM 依赖、
   Node 可直接 require。源文件在仓库根 SKILL/，不在 vscode/ 打包范围内，
   VSIX 里必须有这份拷贝（extension.js 仓库内优先读源文件、打包后回退到这里）。 */
const RENDERER_OUT = path.join(ROOT, 'media', 'render-modern.js');
fs.copyFileSync(SRC, RENDERER_OUT);
console.log('copied ' + SRC + ' -> ' + RENDERER_OUT);
