#!/usr/bin/env node
'use strict';
/* Generate media/modern-render.browser.js — a browser IIFE wrapping the skill's
 * CommonJS render-modern.js. The only `require`s inside render-modern.js are
 * best-effort font-config/font-embed lookups wrapped in try/catch, so a
 * throwing `require` stub makes it fall back to built-in font stacks.
 *
 * Also copies the repo-root index.html (the visual editor UI) into media/, so
 * the packaged VSIX is self-contained: outside the repo, ../index.html does not
 * exist and the editor panel would fail to open. */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, '..', 'SKILL', 'wavedrom-render', 'lib', 'render-modern.js');
const OUT = path.join(ROOT, 'media', 'modern-render.browser.js');
const EDITOR_SRC = path.join(ROOT, '..', 'index.html');
const EDITOR_OUT = path.join(ROOT, 'media', 'editor.html');

const src = fs.readFileSync(SRC, 'utf8');
const out = `/* Generated by scripts/build.js — do not edit. Browser wrapper around
 * SKILL/wavedrom-render/lib/render-modern.js (require calls are stubbed; the
 * renderer falls back to its built-in font stacks). */
(function () {
  var mod = { exports: {} };
  (function (module, exports, require, __dirname, __filename) {
${src}
  })(mod, mod.exports, function (name) {
    throw new Error('browser build: require("' + name + '") is unavailable');
  }, '.', 'render-modern.js');
  window.WaveDromModern = mod.exports;
  /* VS Code 用 <script async> 注入预览脚本，preview.js 可能先于本文件执行完；
     挂上全局后立刻广播，让 preview.js 不必靠执行顺序也能补扫 */
  try { window.dispatchEvent(new Event('wavedrom-renderer-ready')); } catch (e) { /* noop */ }
})();
`;
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, out);
console.log('wrote ' + OUT + ' (' + out.length + ' bytes)');

fs.copyFileSync(EDITOR_SRC, EDITOR_OUT);
console.log('copied ' + EDITOR_SRC + ' -> ' + EDITOR_OUT + ' (' + fs.statSync(EDITOR_OUT).size + ' bytes)');
